console.time('Tour code took');
console.log('Hello Console How R you');
console.log(4+34);
console.log(true);
console.log([34,2,1,4]);
console.log({shri :'this',marks:56});
console.table({shri :'this',marks:56});
console.warn('This is warning');
console.timeEnd('Tour code took');
console.error('This is error');